In [1]:
from flask_ngrok import run_with_ngrok

In [2]:
import os

import flask
app = flask.Flask(__name__)

run_with_ngrok(app)
from flask import Flask, render_template, request

#load model preprocessing
import numpy as np
import pandas as pd
import pickle
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import keras.models
from keras.models import model_from_json

In [3]:
# Load tokenizer for preprocessing
with open('tokenizer.pickle', 'rb') as handle:
    tokenizer = pickle.load(handle)

# Load pre-trained model into memory
json_file = open('model.json','r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

# Load weights into new model
loaded_model.load_weights("model.h5")

In [4]:
def prepData(text):
    # Convert to array
    textDataArray = [text]
    
    # Convert into list with word ids
    Features = tokenizer.texts_to_sequences(textDataArray)
    Features = pad_sequences(Features, 20, padding='post')
    
    return Features

In [5]:
loaded_model.compile(optimizer="Adam",loss='binary_crossentropy',metrics=['accuracy'])

In [6]:
textDataTest = 'Hey! How was dinner last night?'
textTokenizedTest = prepData(textDataTest)
out = np.asscalar(loaded_model.predict(textTokenizedTest))
out

<ipython-input-6-384904600fda>:3: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out = np.asscalar(loaded_model.predict(textTokenizedTest))


0.00013574957847595215

In [7]:
textDataTest = 'Your account has been hacked. Please call 1-800-0000 to speak with a representative'
textTokenizedTest = prepData(textDataTest)
out = np.asscalar(loaded_model.predict(textTokenizedTest))
out

<ipython-input-7-93d70c5ab13b>:3: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out = np.asscalar(loaded_model.predict(textTokenizedTest))


0.9998735189437866

See above. The first message had a 2% probability being spam and the second had a 91% chance. 
Our pre-trained model is working!

In [8]:
# define a predict function as an endpoint 

@app.route('/', methods=['GET','POST'])
def predict():
    
    #whenever the predict method is called, we're going
    #to input the user entered text into the model
    #and return a prediction
    
    if request.method=='POST':
        
        #Note: for local run, we print information to debug and understand how app is working
        
        textData = request.form.get('text_entered')
        print(textData)

        Features = prepData(textData)
        print(Features)
        
        prediction = int((np.asscalar(loaded_model.predict(Features)))*100)
        print(prediction)
        
        #return prediction in new page
        return render_template('prediction.html', prediction=prediction)
    
    else:
        return render_template("search_page.html")   

In [ ]:
if __name__ == "__main__":
    
    #decide what port to run the app in
    port = int(os.environ.get('PORT', 5000))
       
    #run the app locally on the given port
#     app.run(host='127.0.0.1', port=port)
    app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [20/Dec/2021 10:40:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:40:25] "GET /favicon.ico HTTP/1.1" 404 -
<ipython-input-8-846974ead2ee>:20: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  prediction = int((np.asscalar(loaded_model.predict(Features)))*100)
127.0.0.1 - - [20/Dec/2021 10:40:31] "POST / HTTP/1.1" 200 -


#jan Idiot Chelsea Handler Diagnoses Trump With a Disease https://t.co/k8PrqcWTRI https://t.co/dRN35xtSJZ
[[4193 2396   35    4  175  253  175  253    0    0    0    0    0    0
     0    0    0    0    0    0]]
99


127.0.0.1 - - [20/Dec/2021 10:40:42] "GET / HTTP/1.1" 200 -


 * Running on http://72c2-218-248-4-100.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


127.0.0.1 - - [20/Dec/2021 10:40:52] "POST / HTTP/1.1" 200 -


Hii you 
[[3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
2


127.0.0.1 - - [20/Dec/2021 10:40:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:41:26] "POST / HTTP/1.1" 200 -


Hii you got 100 crores lottery . Please comment your credit card
[[   3   63  765  100 3757   13  738  714    0    0    0    0    0    0
     0    0    0    0    0    0]]
75


127.0.0.1 - - [20/Dec/2021 10:41:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:45:14] "POST / HTTP/1.1" 200 -


Hii there. You won 100 crore lottery . please comment your credit card here1!!
[[  68    3  196  765 3574  100 3757   13  738  714    0    0    0    0
     0    0    0    0    0    0]]
99


127.0.0.1 - - [20/Dec/2021 10:45:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:46:13] "POST / HTTP/1.1" 200 -


You won Iphone13 pro please send some money to the account 11345676544. You will get it
[[   3  196 4041  100   69  130  240    2    5  365    3   27   34   14
     0    0    0    0    0    0]]
27


127.0.0.1 - - [20/Dec/2021 10:46:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:46:43] "POST / HTTP/1.1" 200 -


You won Iphone13 pro .please send some money to the account 113456765442312
[[   3  196 4041  100   69  130  240    2    5  365    0    0    0    0
     0    0    0    0    0    0]]
22


127.0.0.1 - - [20/Dec/2021 10:46:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:49:05] "POST / HTTP/1.1" 200 -


You won Iphone 11 as a lottery. send money using this link "https://www.investopedia.com/terms/a/accountsreceivable.asp".
[[   3  196 4495  880   75    4   69  240 1078   39 1174  160  187 1008
     4 4137    0    0    0    0]]
99


127.0.0.1 - - [20/Dec/2021 10:49:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:49:34] "POST / HTTP/1.1" 200 -


You won Iphone 11 as a lottery. send money using this link.
[[   3  196 4495  880   75    4   69  240 1078   39 1174    0    0    0
     0    0    0    0    0    0]]
1


127.0.0.1 - - [20/Dec/2021 10:49:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:50:00] "POST / HTTP/1.1" 200 -


You won Iphone 11 as a lottery. send money using this link.#iphone11winner
[[   3  196 4495  880   75    4   69  240 1078   39 1174    0    0    0
     0    0    0    0    0    0]]
1


127.0.0.1 - - [20/Dec/2021 10:50:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:50:27] "POST / HTTP/1.1" 200 -


You won Iphone 11 as a lottery. send money using this link.#iphone11winner #iphone11 #winner
[[   3  196 4495  880   75    4   69  240 1078   39 1174  678    0    0
     0    0    0    0    0    0]]
2


127.0.0.1 - - [20/Dec/2021 10:50:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:51:55] "POST / HTTP/1.1" 200 -


You won Iphone 11 as a lottery. send money using this link #Mr.Beast#Pubg#BGMI#Tournamentwinner
[[   3  196 4495  880   75    4   69  240 1078   39 1174 1096    0    0
     0    0    0    0    0    0]]
1


127.0.0.1 - - [20/Dec/2021 10:52:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:52:09] "POST / HTTP/1.1" 200 -


Hii there
[[68  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
1


127.0.0.1 - - [20/Dec/2021 10:52:12] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:52:21] "POST / HTTP/1.1" 200 -


you won lottery
[[  3 196   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]]
2


127.0.0.1 - - [20/Dec/2021 10:52:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:52:58] "POST / HTTP/1.1" 200 -


You won Iphone 11 as a lottery. send money using this link "https://www.investopedia.com/terms/a/accountsreceivable.asp".
[[   3  196 4495  880   75    4   69  240 1078   39 1174  160  187 1008
     4 4137    0    0    0    0]]
99


127.0.0.1 - - [20/Dec/2021 10:53:01] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:53:50] "POST / HTTP/1.1" 200 -


You won Iphone 11 as a lottery. send money using this link "https://www.investopedia.com/terms/a/accountsreceivable.asp" refer to this "vishnu@gmail.com"..
[[   3  196 4495  880   75    4   69  240 1078   39 1174  160  187 1008
     4 4137    2   39  187    0]]
100


127.0.0.1 - - [20/Dec/2021 10:53:57] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:54:09] "POST / HTTP/1.1" 200 -


You won Iphone 11 as a lottery. send money using this link "".
[[   3  196 4495  880   75    4   69  240 1078   39 1174    0    0    0
     0    0    0    0    0    0]]
1


127.0.0.1 - - [20/Dec/2021 10:54:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:54:44] "POST / HTTP/1.1" 200 -


You won Iphone 11 as a lottery. Message to this mail "vishnu@gmail.com".
[[   3  196 4495  880   75    4  150    2   39  482  187    0    0    0
     0    0    0    0    0    0]]
27


127.0.0.1 - - [20/Dec/2021 10:54:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:55:40] "POST / HTTP/1.1" 200 -


Justice for rape aganist vishnu @nirbhaya#savevishnu#protectgirls
[[12  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
2


127.0.0.1 - - [20/Dec/2021 10:55:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:56:19] "POST / HTTP/1.1" 200 -


Pre-sale starts on 12 Nov 1.30pm IST / 12.00am PST 😍 only on https://t.co/RAN8aJQsD3  . . SunnyLeone NFT NFTLaunch NFTCommunity NFTGiveaways nftcollector NFTArt nftartist nftcollectibles @SunnyLeoneNFT https://t.co/DAvF6XDP3B
[[4470 1138 1064   19  957  120  957   64   19  175  253  175  253    0
     0    0    0    0    0    0]]
100


127.0.0.1 - - [20/Dec/2021 10:56:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:56:31] "POST / HTTP/1.1" 200 -


#jan Idiot Chelsea Handler Diagnoses Trump With a Disease https://t.co/k8PrqcWTRI https://t.co/dRN35xtSJZ
[[4193 2396   35    4  175  253  175  253    0    0    0    0    0    0
     0    0    0    0    0    0]]
99


127.0.0.1 - - [20/Dec/2021 10:56:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:57:04] "POST / HTTP/1.1" 200 -


you have won the lottery ticket of 100 crores. Refer this link "https://www.investopedia.com/terms/a/accountsreceivable.asp"
[[   3   17  196    5 1505   15  765   39 1174  160  187 1008    4 4137
     0    0    0    0    0    0]]
100


127.0.0.1 - - [20/Dec/2021 10:57:10] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:57:47] "POST / HTTP/1.1" 200 -


You won 100 crores as a lottery. Message me at "message@gmail.com"
[[  3 196 765  75   4 150  10  28 150 187   0   0   0   0   0   0   0   0
    0   0]]
65


127.0.0.1 - - [20/Dec/2021 10:58:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 10:59:28] "POST / HTTP/1.1" 200 -


The Guardian: Trump's Tweets Keep U.S. Manufacturers on Their Toes #MAGA #AmericaFirst #PresidentTrump  https://t.co/V0sQskFolF https://t.co/jhxaxLDowy
[[   5  192    6  210   19  852 2023  175  253  175  253    0    0    0
     0    0    0    0    0    0]]
57


127.0.0.1 - - [20/Dec/2021 10:59:57] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 11:00:00] "POST / HTTP/1.1" 200 -


Happy #TideTuesday everyone I live you  @TheTideAustin @TheTideDrew @TheTideLevi @TheTideNate
[[149 587   1 275   3   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]]
0


127.0.0.1 - - [20/Dec/2021 11:00:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 11:00:43] "POST / HTTP/1.1" 200 -


I was really putting my money on the hookers
[[   1   61  174 1778   11  240   19    5    0    0    0    0    0    0
     0    0    0    0    0    0]]
0


127.0.0.1 - - [20/Dec/2021 11:00:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 11:01:01] "POST / HTTP/1.1" 200 -


#jan Idiot Chelsea Handler Diagnoses Trump With a Disease https://t.co/k8PrqcWTRI https://t.co/dRN35xtSJZ
[[4193 2396   35    4  175  253  175  253    0    0    0    0    0    0
     0    0    0    0    0    0]]
99


127.0.0.1 - - [20/Dec/2021 11:01:03] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 11:17:14] "POST / HTTP/1.1" 200 -


#jan Idiot Chelsea Handler Diagnoses Trump With a Disease https://t.co/k8PrqcWTRI https://t.co/dRN35xtSJZ
[[4193 2396   35    4  175  253  175  253    0    0    0    0    0    0
     0    0    0    0    0    0]]
99


127.0.0.1 - - [20/Dec/2021 11:18:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 11:18:10] "POST / HTTP/1.1" 200 -


#jan Idiot Chelsea Handler Diagnoses Trump With a Disease https://t.co/k8PrqcWTRI https://t.co/dRN35xtSJZ
[[4193 2396   35    4  175  253  175  253    0    0    0    0    0    0
     0    0    0    0    0    0]]
99


127.0.0.1 - - [20/Dec/2021 11:18:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 11:18:19] "POST / HTTP/1.1" 200 -


Hi there
[[90 68  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
0


127.0.0.1 - - [20/Dec/2021 11:18:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 11:18:42] "POST / HTTP/1.1" 200 -


You won 100 crores as a lottery. Message me at "message@gmail.com"
[[  3 196 765  75   4 150  10  28 150 187   0   0   0   0   0   0   0   0
    0   0]]
65


127.0.0.1 - - [20/Dec/2021 12:02:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 12:02:59] "POST / HTTP/1.1" 200 -


You won 100 crores as a lottery. Message me at "message@gmail.com"
[[  3 196 765  75   4 150  10  28 150 187   0   0   0   0   0   0   0   0
    0   0]]
65


127.0.0.1 - - [20/Dec/2021 12:03:01] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 12:03:10] "POST / HTTP/1.1" 200 -


Pre-sale starts on 12 Nov 1.30pm IST / 12.00am PST 😍 only on https://t.co/RAN8aJQsD3  . . #SunnyLeone #NFT #NFTLaunch #NFTCommunity #NFTGiveaways #nftcollector #NFTArt #nftartist #nftcollectibles @SunnyLeoneNFT https://t.co/DAvF6XDP3B
[[4470 1138 1064   19  957  120  957   64   19  175  253  175  253    0
     0    0    0    0    0    0]]
100


127.0.0.1 - - [20/Dec/2021 12:03:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 12:03:41] "POST / HTTP/1.1" 200 -


You won Iphone 11 as a lottery. send money using this link "https://www.investopedia.com/terms/a/accountsreceivable.asp".
[[   3  196 4495  880   75    4   69  240 1078   39 1174  160  187 1008
     4 4137    0    0    0    0]]
99


127.0.0.1 - - [20/Dec/2021 12:04:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2021 12:38:08] "POST / HTTP/1.1" 200 -


#justice for batch 10
[[  12 2842  355    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0]]
2


127.0.0.1 - - [20/Dec/2021 12:38:12] "GET / HTTP/1.1" 200 -
